version: "3.8"

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=jsencoder
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - nodeNETWORK

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root1234
    depends_on:
      - db
    networks:
      - nodeNETWORK

  nodejs-app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    restart: always
    hostname: nodejs-app
    ports:
      - "5002:5002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=jsencoder
    networks:
      - nodeNETWORK

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    # build:
    #   context: .
    #   dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs-app
    networks:
      - nodeNETWORK

networks:
  nodeNETWORK:
    external: true

volumes:
  db_data:
