# FROM nginx
# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD [ "nginx", "-g", "demon off;"]
# Use an Ubuntu-based image
# FROM ubuntu

# # Update package lists and install the required networking tools
# RUN apt-get update && \
#     apt-get install -y net-tools iproute2 lsof

# # Remove the default NGINX configuration file
# RUN rm /etc/nginx/conf.d/default.conf

# # Copy your custom NGINX configuration file into the container
# COPY ./default.conf /etc/nginx/conf.d/

# # Expose port 80
# EXPOSE 80

# # Start NGINX with the correct daemon option
# CMD ["nginx", "-g", "daemon off;"]


# Use nginx image based on Alpine Linux
# FROM nginx:alpine

# # Copy custom HTML file to the container
# COPY index.html /usr/share/nginx/html

# # Copy custom nginx.conf file to the container and overwrite the default.conf file
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# # Expose port 80 for web server
# EXPOSE 80

# # Start nginx server
# CMD ["nginx", "-g", "daemon off;"]